sudo: false
language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION package doc
scala:
  - 2.11.12
  - 2.12.10
  - 2.13.1
jdk:
  - openjdk8
env:
  - SCALAJS_VERSION=0.6.29
  - SCALAJS_VERSION=1.0.0-M8

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
